import './globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { MultiplayerInit } from '@/src/features/multiplayer/multiplayer-init'
import { SaveClearedNotification } from '@/src/features/setup/save-cleared-notification'

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'ArtSurv',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SaveClearedNotification />
        <MultiplayerInit />
        {children}
      </body>
    </html>
  )
}
